name: android_util_log
description: "A utility library for Android log. Built with dart's experimental jni"
version: 0.1.0
repository: https://github.com/dash-chan/packages/tree/main/packages/android_util_log
issue_tracker: https://github.com/dash-chan/packages/labels/p%3Aandroid_util_log
documentation: https://pub.dev/documentation/android_util_log/latest/

topics:
  - android
  - jni
  - utils

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
