name: webview_refresher
description: "bring pull to refresh feature to official webview plugin"
version: 0.1.1
homepage: https://github.com/dash-chan/packages/tree/main/packages/webview_refresher

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0